### ISSUE TITLE
Ytdl isn't working 

### ISSUE THREAD

**Issue by Better-Than-You** [FantoX001/Atlas-MD#119]
Recently discovered that the ytdl commands aren't working. It gives details of the video, and the links well, although that's all. It crashes before sending the mp3/mp4. The downloader being a notable feature of the bot, seeing it's not working is kinda disappointing.

**Comment by FantoX001** [comment]
Ok thank you for notifying I will look into this matter

**Comment by Kai0071** [comment]
Error: Can't cut unsupported JSON (no matching closing bracket found)

I can't find out the issues. The issues have in module.

**Comment by Better-Than-You** [comment]
I'm closing this issue now, as the ytdl is working again.
