### ISSUE TITLE
TypeError: cannot read properties of undefined (reading 'BotName')

### ISSUE THREAD

**Issue by Hasif-bit** [FantoX001/Atlas-MD#29]
Hello I'm not sure if I accidentally edited something I shouldn't but I can't start the bot it says TypeError: cannot read properties of undefined (reading 'BotName') and I can't find the problem please help me
![Screenshot_20230223_211124](https://user-images.githubusercontent.com/77277332/220916667-dd2697c2-2718-492d-8c27-3f3c05a8276b.jpg)

**Comment by FantoX001** [comment]
@Hasif-bit bro did you Forked it today ? Or before today ?

Because today I pushed an update and fixed some bugs and added more features. If you are using an old fork you are requested to sumc the GitHub repo to update it.

Also, if this issue still continues then you might using public MongoDb url. To fix it you have to create your own MongoDb url and use.

Thank you.

**Comment by NekoSenpai69** [comment]
Hello I am a mod of atlas I got same error when I didn't deploy the bot i think u did some mistake but when I start it from start it worked

**Comment by NekoSenpai69** [comment]
Please import the file again try to deploy it correctly

**Comment by Hasif-bit** [comment]
> 

Before today. Thank you I will refork and deploy it

**Comment by Hasif-bit** [comment]
> @Hasif-bit bro did you Forked it today ? Or before today ?
> 
> Because today I pushed an update and fixed some bugs and added more features. If you are using an old fork you are requested to sumc the GitHub repo to update it.
> 
> Also, if this issue still continues then you might using public MongoDb url. To fix it you have to create your own MongoDb url and use.
> 
> Thank you.

Also can you give me an instruction how to create MongoDb url ? Bc I already created my account but I don't have any idea how to get the url

**Comment by NekoSenpai69** [comment]
Fantox will create a video about creating your own mongodb url please wait until then subscribe his channel to get instant updates channel name :- fantox gaming


Thank you

**Comment by NekoSenpai69** [comment]
> > Fantox will create a video about creating your own mongodb url please wait until then subscribe his channel to get instant updates channel name :- fantox gaming
> > Thank you
> 
> Bhaiya mera khud ka url hai aur 🥲

Shi se url nhi banaya hai isi liye eisa ho rha hai

**Comment by NekoSenpai69** [comment]
Shi se url nhi banaya isi liye arha hai mujhe v mila tha same error jab mene url thik se nhi banaya tha url mein galti hai ya secret keys dalneme galti kar rha hai tu🥲 aur kuchh nhi janta main

**Comment by NekoSenpai69** [comment]
mein ja rha hu ab Gmail ka  notification off rakhne parte parte bar bar notification arha hai notes mobile pe hai 🥲
