### ISSUE TITLE
Command Rejected ! Bot is in Self mode !

### ISSUE THREAD

**Issue by RuberDucky** [FantoX001/Atlas-MD#61]
i host your bot on windows i got error here and when i send the -help it just react but not send the menu please tell me what should do

**Comment by FantoX001** [comment]
Easy fix.

1. Use your own MongoDb url
2. Make sure you have added your number in mods.
3. Go to any group and type **-mode public** to make bot public.

**Comment by RuberDucky** [comment]
how to find our own mongodb url wiil you teach me sir

**Comment by FantoX001** [comment]
> how to find our own mongodb url wiil you teach me sir
> 

https://youtube.com/shorts/pIHvoXkwmq4?feature=share

Here's my short tutorial on how to create a MongoDb url.

**Comment by Devime69** [comment]
> 
Search fantox gaming and watch the tutorial of how to create mongodb url

**Comment by Devime69** [comment]
Pull request ta check koro fox girl api ta dead ota change korechhi accept koro

**Comment by RuberDucky** [comment]
i still not getting menu, even i tried lot of times

**Comment by Devime69** [comment]
It's not an error, actually this is a bug of latest official WhatsApp version wait some days to get new update or use WhatsApp buisness or mod apk personally I doesn't prefer to use mod whatsapp because of ban

**Comment by RuberDucky** [comment]
Alright sir Thanks for your time, I really appreciate that.
