### ISSUE TITLE
Why my screen is saying "dotenv not found"

### ISSUE THREAD

**Issue by Kali-176** [FantoX001/Atlas-MD#82]

**Comment by NekoSenpai69** [comment]
npm i dotenv


Write down that in terminal

**Comment by FantoX001** [comment]
Installation: `npm i dotenv`

import inside a file: `require("dotenv").config();`

In Atlas there's no such issue present until you edited it youreself in wrong way.

**Comment by Kali-176** [comment]
> Installation: `npm i dotenv`
> 
> import inside a file: `require("dotenv").config();`
> 
> In Atlas there's no such issue present until you edited it youreself in wrong way.




Btw my repl now isn't showing that error but the deploying isn't starting either .... Do you know why the problem occurred. I created new fork and tried too but yet in replit it's not working.
